FROM debian:bookworm-slim

# Add some essentials
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    curl \
    bash-completion && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure Git
RUN git config --global --add safe.directory /workspace

# Setup bash completion
RUN cat <<'EOF' >> /root/.bashrc

# Source bash completion
. /usr/share/bash-completion/bash_completion
EOF

# Setup a slightly nicer shell prompt
RUN curl -sS https://starship.rs/install.sh -o /tmp/install-starship.sh && \
    sh /tmp/install-starship.sh -y && \
    rm /tmp/install-starship.sh

# Configure prompt
ENV STARSHIP_CONFIG="/root/.config/starship.toml"
RUN cat <<'EOF' >> /root/.bashrc

# Initialize the starship prompt
eval "$(starship init bash)"
EOF
